### ISSUE TITLE
Can't use With.Any<int>

### ISSUE THREAD

**Issue by michaelmcneilnet** [johnmwright/Fakes.Contrib#1]
I would like to be able to use With.Any with value types. Most of my methods under test take an int and I want to check that it was not called at all, regardless of the parameter.

I would like to do something like:

AssertWasNotCalled(stub => stub.MyMethod(With.Any&lt;int&gt;()));

but it looks like the With.Any extension constrains the generic type to be a class.

Is there any workaround possible?

**Comment by fvilers** [comment]
Hi Michael,

Unfortunately, at this time, Fakes.Contrib doesn't support verification against a basic type like int or string.

Currently, I don't have any time to add this feature but pull requests are welcome.

Regards,
Fabian
